Fix dev dependencies to be able to draw plots in notebooks
	Fixes following error when trying to draw a plot in a notebook:
	ValueError: Mime type rendering requires nbformat(...) but it is not installed

Signed-off-by: ai-qui <184963772+ai-qui@users.noreply.github.com>